// Code generated by me. DO NOT EDIT.

package goIdlIop

import __fmt__ "fmt"
import __goIdlCorba__ "github.com/bhbosman/goIdlCorba"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// TypeDef declaration: "IOP::ProfileId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ProfileId" from: "uint32"
type IopProfileId uint32

//noinspection GoSnakeCaseUsage
type IopProfileId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopProfileIdId_Const = "IDL:omg.org/IOP/ProfileId:1.0"

func (self IopProfileId_Helper) Id() string {
	return IopProfileIdId_Const
}

func (self IopProfileId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopProfileId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Constant declaration: "IOP::TAG_INTERNET_IOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInternetIop uint32 = 0

// Constant declaration: "IOP::TAG_MULTIPLE_COMPONENTS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagMultipleComponents uint32 = 1

// Constant declaration: "IOP::TAG_SCCP_IOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSccpIop uint32 = 2

// Constant declaration: "IOP::TAG_UIPMC", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagUipmc uint32 = 3

// Struct declaration: "IOP::TaggedProfile", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedProfile struct {
	__goidl__.IdlObject
	Tag uint32 `json:"Tag"`
	ProfileData __goIdlCorba__.CorbaOctetSeq `json:"ProfileData"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedProfileId_Const = "IDL:omg.org/IOP/TaggedProfile:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopTaggedProfile() *IopTaggedProfile {
	//noinspection GoRedundantConversion
	return &IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopTaggedProfile(
	//"StructDclAllParamsConstructorParamService"
	Tag uint32,
	//"StructDclAllParamsConstructorParamService"
	ProfileData __goIdlCorba__.CorbaOctetSeq) *IopTaggedProfile {
	//noinspection GoRedundantConversion
	return &IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileId_Const,
		},
		Tag: Tag,
		ProfileData: ProfileData,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopTaggedProfile(randomGenerator __goidl__.IRandomDataGenerator) *IopTaggedProfile {
	//noinspection GoRedundantConversion
	return &IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopTaggedProfile)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopTaggedProfile)(nil)), "Array"),
	},
	}
}

func (self *IopTaggedProfile) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedProfile) GoString() string {
	return self.String()
}

func (self *IopTaggedProfile) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Tag, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ProfileData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfile) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfile) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Tag)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ProfileData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedProfile_Helper struct {
}

// Struct declaration: "IOP::TaggedProfileSeq", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedProfileSeq struct {
	__goidl__.IdlObject
	Array IopTaggedProfile `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedProfileSeqId_Const = "IDL:IOP/TaggedProfileSeq:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopTaggedProfileSeq() *IopTaggedProfileSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedProfileSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileSeqId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedProfile" Scope: "IdlStruct"
		Array: IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopTaggedProfileSeq(
	//"StructDclAllParamsConstructorParamService"
	Array IopTaggedProfile) *IopTaggedProfileSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedProfileSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileSeqId_Const,
		},
		Array: Array,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopTaggedProfileSeq(randomGenerator __goidl__.IRandomDataGenerator) *IopTaggedProfileSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedProfileSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedProfileSeqId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedProfile" Scope: "IdlStruct"
		Array: IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopTaggedProfileSeq)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopTaggedProfileSeq)(nil)), "Array"),
	},
	},
	}
}

func (self *IopTaggedProfileSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedProfileSeq) GoString() string {
	return self.String()
}

func (self *IopTaggedProfileSeq) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Array.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfileSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfileSeq) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedProfileSeq_Helper struct {
}

// Struct declaration: "IOP::IOR", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopIor struct {
	__goidl__.IdlObject
	TypeId string `json:"TypeId"`
	Profiles IopTaggedProfileSeq `json:"Profiles"`
}

//noinspection GoSnakeCaseUsage
const IopIorId_Const = "IDL:omg.org/IOP/IOR:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopIor() *IopIor {
	//noinspection GoRedundantConversion
	return &IopIor{
		IdlObject: __goidl__.IdlObject{
			Id: IopIorId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_id", Type: "IdlString" Scope: "StringType"
		TypeId: "",
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profiles", Type: "IOP::TaggedProfileSeq" Scope: "IdlStruct"
		Profiles: IopTaggedProfileSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedProfile" Scope: "IdlStruct"
		Array: IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopIor(
	//"StructDclAllParamsConstructorParamService"
	TypeId string,
	//"StructDclAllParamsConstructorParamService"
	Profiles IopTaggedProfileSeq) *IopIor {
	//noinspection GoRedundantConversion
	return &IopIor{
		IdlObject: __goidl__.IdlObject{
			Id: IopIorId_Const,
		},
		TypeId: TypeId,
		Profiles: Profiles,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopIor(randomGenerator __goidl__.IRandomDataGenerator) *IopIor {
	//noinspection GoRedundantConversion
	return &IopIor{
		IdlObject: __goidl__.IdlObject{
			Id: IopIorId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "type_id", Type: "IdlString" Scope: "StringType"
		TypeId: randomGenerator.StringTypeValue(__reflect__.TypeOf((*IopIor)(nil)), "TypeId"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profiles", Type: "IOP::TaggedProfileSeq" Scope: "IdlStruct"
		Profiles: IopTaggedProfileSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedProfile" Scope: "IdlStruct"
		Array: IopTaggedProfile{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ProfileId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopIor)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "profile_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ProfileData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopIor)(nil)), "Array"),
	},
	},
	},
	}
}

func (self *IopIor) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopIor) GoString() string {
	return self.String()
}

func (self *IopIor) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.TypeId, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Profiles.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopIor) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopIor) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.TypeId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Profiles.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopIor_Helper struct {
}

// TypeDef declaration: "IOP::ComponentId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ComponentId" from: "uint32"
type IopComponentId uint32

//noinspection GoSnakeCaseUsage
type IopComponentId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopComponentIdId_Const = "IDL:omg.org/IOP/ComponentId:1.0"

func (self IopComponentId_Helper) Id() string {
	return IopComponentIdId_Const
}

func (self IopComponentId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopComponentId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Struct declaration: "IOP::ComponentData", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopComponentData struct {
	__goIdlCorba__.CorbaOctetSeq
}

//noinspection GoSnakeCaseUsage
const IopComponentDataId_Const = "IDL:IOP/ComponentData:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopComponentData() *IopComponentData {
	//noinspection GoRedundantConversion
	return &IopComponentData{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopComponentDataId_Const,
			},
			// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
			Array: 0,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopComponentData(
	//"StructDclAllParamsConstructorParamService"
	Array byte) *IopComponentData {
	//noinspection GoRedundantConversion
	return &IopComponentData{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopComponentDataId_Const,
			},
			Array: Array,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopComponentData(randomGenerator __goidl__.IRandomDataGenerator) *IopComponentData {
	//noinspection GoRedundantConversion
	return &IopComponentData{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopComponentDataId_Const,
			},
			// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
			Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopComponentData)(nil)), "Array"),
		},
	}
}

func (self *IopComponentData) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopComponentData) GoString() string {
	return self.String()
}

func (self *IopComponentData) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.CorbaOctetSeq.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopComponentData) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopComponentData) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.CorbaOctetSeq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopComponentData_Helper struct {
}

// Struct declaration: "IOP::TaggedComponent", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedComponent struct {
	__goidl__.IdlObject
	Tag uint32 `json:"Tag"`
	ComponentData IopComponentData `json:"ComponentData"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedComponentId_Const = "IDL:omg.org/IOP/TaggedComponent:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopTaggedComponent() *IopTaggedComponent {
	//noinspection GoRedundantConversion
	return &IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopTaggedComponent(
	//"StructDclAllParamsConstructorParamService"
	Tag uint32,
	//"StructDclAllParamsConstructorParamService"
	ComponentData IopComponentData) *IopTaggedComponent {
	//noinspection GoRedundantConversion
	return &IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentId_Const,
		},
		Tag: Tag,
		ComponentData: ComponentData,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopTaggedComponent(randomGenerator __goidl__.IRandomDataGenerator) *IopTaggedComponent {
	//noinspection GoRedundantConversion
	return &IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopTaggedComponent)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopTaggedComponent)(nil)), "Array"),
	},
	},
	}
}

func (self *IopTaggedComponent) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedComponent) GoString() string {
	return self.String()
}

func (self *IopTaggedComponent) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Tag, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ComponentData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponent) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponent) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Tag)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ComponentData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedComponent_Helper struct {
}

// Struct declaration: "IOP::TaggedComponentSeq", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedComponentSeq struct {
	__goidl__.IdlObject
	Array IopTaggedComponent `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedComponentSeqId_Const = "IDL:IOP/TaggedComponentSeq:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopTaggedComponentSeq() *IopTaggedComponentSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedComponentSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentSeqId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedComponent" Scope: "IdlStruct"
		Array: IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopTaggedComponentSeq(
	//"StructDclAllParamsConstructorParamService"
	Array IopTaggedComponent) *IopTaggedComponentSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedComponentSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentSeqId_Const,
		},
		Array: Array,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopTaggedComponentSeq(randomGenerator __goidl__.IRandomDataGenerator) *IopTaggedComponentSeq {
	//noinspection GoRedundantConversion
	return &IopTaggedComponentSeq{
		IdlObject: __goidl__.IdlObject{
			Id: IopTaggedComponentSeqId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedComponent" Scope: "IdlStruct"
		Array: IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopTaggedComponentSeq)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopTaggedComponentSeq)(nil)), "Array"),
	},
	},
	},
	}
}

func (self *IopTaggedComponentSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedComponentSeq) GoString() string {
	return self.String()
}

func (self *IopTaggedComponentSeq) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Array.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponentSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponentSeq) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedComponentSeq_Helper struct {
}

// Struct declaration: "IOP::MultipleComponentProfile", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopMultipleComponentProfile struct {
	__goidl__.IdlObject
	Array IopTaggedComponent `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IopMultipleComponentProfileId_Const = "IDL:IOP/MultipleComponentProfile:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopMultipleComponentProfile() *IopMultipleComponentProfile {
	//noinspection GoRedundantConversion
	return &IopMultipleComponentProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopMultipleComponentProfileId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedComponent" Scope: "IdlStruct"
		Array: IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopMultipleComponentProfile(
	//"StructDclAllParamsConstructorParamService"
	Array IopTaggedComponent) *IopMultipleComponentProfile {
	//noinspection GoRedundantConversion
	return &IopMultipleComponentProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopMultipleComponentProfileId_Const,
		},
		Array: Array,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopMultipleComponentProfile(randomGenerator __goidl__.IRandomDataGenerator) *IopMultipleComponentProfile {
	//noinspection GoRedundantConversion
	return &IopMultipleComponentProfile{
		IdlObject: __goidl__.IdlObject{
			Id: IopMultipleComponentProfileId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::TaggedComponent" Scope: "IdlStruct"
		Array: IopTaggedComponent{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "tag", Type: "IOP::ComponentId" Scope: "IdlTypedef"
		Tag: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopMultipleComponentProfile)(nil)), "Tag"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "component_data", Type: "IOP::ComponentData" Scope: "IdlStruct"
		ComponentData: IopComponentData{
	CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopMultipleComponentProfile)(nil)), "Array"),
	},
	},
	},
	}
}

func (self *IopMultipleComponentProfile) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopMultipleComponentProfile) GoString() string {
	return self.String()
}

func (self *IopMultipleComponentProfile) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Array.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopMultipleComponentProfile) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopMultipleComponentProfile) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	return nil
}

//noinspection GoSnakeCaseUsage
type IopMultipleComponentProfile_Helper struct {
}

// Struct declaration: "IOP::ObjectKey", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopObjectKey struct {
	__goIdlCorba__.CorbaOctetSeq
}

//noinspection GoSnakeCaseUsage
const IopObjectKeyId_Const = "IDL:IOP/ObjectKey:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopObjectKey() *IopObjectKey {
	//noinspection GoRedundantConversion
	return &IopObjectKey{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopObjectKeyId_Const,
			},
			// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
			Array: 0,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopObjectKey(
	//"StructDclAllParamsConstructorParamService"
	Array byte) *IopObjectKey {
	//noinspection GoRedundantConversion
	return &IopObjectKey{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopObjectKeyId_Const,
			},
			Array: Array,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopObjectKey(randomGenerator __goidl__.IRandomDataGenerator) *IopObjectKey {
	//noinspection GoRedundantConversion
	return &IopObjectKey{
		CorbaOctetSeq: __goIdlCorba__.CorbaOctetSeq{
			IdlObject: __goidl__.IdlObject{
				Id: IopObjectKeyId_Const,
			},
			// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
			Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopObjectKey)(nil)), "Array"),
		},
	}
}

func (self *IopObjectKey) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopObjectKey) GoString() string {
	return self.String()
}

func (self *IopObjectKey) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.CorbaOctetSeq.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopObjectKey) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopObjectKey) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.CorbaOctetSeq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopObjectKey_Helper struct {
}

// Constant declaration: "IOP::TAG_ORB_TYPE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagOrbType uint32 = 0

// Constant declaration: "IOP::TAG_CODE_SETS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCodeSets uint32 = 1

// Constant declaration: "IOP::TAG_POLICIES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagPolicies uint32 = 2

// Constant declaration: "IOP::TAG_ALTERNATE_IIOP_ADDRESS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagAlternateIiopAddress uint32 = 3

// Constant declaration: "IOP::TAG_ASSOCIATION_OPTIONS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagAssociationOptions uint32 = 13

// Constant declaration: "IOP::TAG_SEC_NAME", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSecName uint32 = 14

// Constant declaration: "IOP::TAG_SPKM_1_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSpkm1SecMech uint32 = 15

// Constant declaration: "IOP::TAG_SPKM_2_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSpkm2SecMech uint32 = 16

// Constant declaration: "IOP::TAG_KerberosV5_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagKerberosV5SecMech uint32 = 17

// Constant declaration: "IOP::TAG_CSI_ECMA_Secret_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaSecretSecMech uint32 = 18

// Constant declaration: "IOP::TAG_CSI_ECMA_Hybrid_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaHybridSecMech uint32 = 19

// Constant declaration: "IOP::TAG_SSL_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSslSecTrans uint32 = 20

// Constant declaration: "IOP::TAG_CSI_ECMA_Public_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaPublicSecMech uint32 = 21

// Constant declaration: "IOP::TAG_GENERIC_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGenericSecMech uint32 = 22

// Constant declaration: "IOP::TAG_FIREWALL_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagFirewallTrans uint32 = 23

// Constant declaration: "IOP::TAG_SCCP_CONTACT_INFO", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSccpContactInfo uint32 = 24

// Constant declaration: "IOP::TAG_JAVA_CODEBASE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagJavaCodebase uint32 = 25

// Constant declaration: "IOP::TAG_TRANSACTION_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagTransactionPolicy uint32 = 26

// Constant declaration: "IOP::TAG_MESSAGE_ROUTER", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagMessageRouter uint32 = 30

// Constant declaration: "IOP::TAG_OTS_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagOtsPolicy uint32 = 31

// Constant declaration: "IOP::TAG_INV_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInvPolicy uint32 = 32

// Constant declaration: "IOP::TAG_CSI_SEC_MECH_LIST", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiSecMechList uint32 = 33

// Constant declaration: "IOP::TAG_NULL_TAG", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagNullTag uint32 = 34

// Constant declaration: "IOP::TAG_SECIOP_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSeciopSecTrans uint32 = 35

// Constant declaration: "IOP::TAG_TLS_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagTlsSecTrans uint32 = 36

// Constant declaration: "IOP::TAG_ACTIVITY_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagActivityPolicy uint32 = 37

// Constant declaration: "IOP::TAG_RMI_CUSTOM_MAX_STREAM_FORMAT", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagRmiCustomMaxStreamFormat uint32 = 38

// Constant declaration: "IOP::TAG_GROUP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGroup uint32 = 39

// Constant declaration: "IOP::TAG_GROUP_IIOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGroupIiop uint32 = 40

// Constant declaration: "IOP::TAG_COMPLETE_OBJECT_KEY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCompleteObjectKey uint32 = 5

// Constant declaration: "IOP::TAG_ENDPOINT_ID_POSITION", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagEndpointIdPosition uint32 = 6

// Constant declaration: "IOP::TAG_LOCATION_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagLocationPolicy uint32 = 12

// Constant declaration: "IOP::TAG_DCE_STRING_BINDING", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceStringBinding uint32 = 100

// Constant declaration: "IOP::TAG_DCE_BINDING_NAME", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceBindingName uint32 = 101

// Constant declaration: "IOP::TAG_DCE_NO_PIPES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceNoPipes uint32 = 102

// Constant declaration: "IOP::TAG_DCE_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceSecMech uint32 = 103

// Constant declaration: "IOP::TAG_INET_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInetSecTrans uint32 = 123

// TypeDef declaration: "IOP::ServiceId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ServiceId" from: "uint32"
type IopServiceId uint32

//noinspection GoSnakeCaseUsage
type IopServiceId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopServiceIdId_Const = "IDL:omg.org/IOP/ServiceId:1.0"

func (self IopServiceId_Helper) Id() string {
	return IopServiceIdId_Const
}

func (self IopServiceId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopServiceId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Struct declaration: "IOP::ServiceContext", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopServiceContext struct {
	__goidl__.IdlObject
	ContextId uint32 `json:"ContextId"`
	ContextData __goIdlCorba__.CorbaOctetSeq `json:"ContextData"`
}

//noinspection GoSnakeCaseUsage
const IopServiceContextId_Const = "IDL:omg.org/IOP/ServiceContext:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopServiceContext() *IopServiceContext {
	//noinspection GoRedundantConversion
	return &IopServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_id", Type: "IOP::ServiceId" Scope: "IdlTypedef"
		ContextId: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ContextData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopServiceContext(
	//"StructDclAllParamsConstructorParamService"
	ContextId uint32,
	//"StructDclAllParamsConstructorParamService"
	ContextData __goIdlCorba__.CorbaOctetSeq) *IopServiceContext {
	//noinspection GoRedundantConversion
	return &IopServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextId_Const,
		},
		ContextId: ContextId,
		ContextData: ContextData,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopServiceContext(randomGenerator __goidl__.IRandomDataGenerator) *IopServiceContext {
	//noinspection GoRedundantConversion
	return &IopServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_id", Type: "IOP::ServiceId" Scope: "IdlTypedef"
		ContextId: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopServiceContext)(nil)), "ContextId"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ContextData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopServiceContext)(nil)), "Array"),
	},
	}
}

func (self *IopServiceContext) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopServiceContext) GoString() string {
	return self.String()
}

func (self *IopServiceContext) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.ContextId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ContextData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContext) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContext) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.ContextId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ContextData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopServiceContext_Helper struct {
}

// Struct declaration: "IOP::ServiceContextList", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopServiceContextList struct {
	__goidl__.IdlObject
	Array IopServiceContext `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const IopServiceContextListId_Const = "IDL:IOP/ServiceContextList:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopServiceContextList() *IopServiceContextList {
	//noinspection GoRedundantConversion
	return &IopServiceContextList{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextListId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::ServiceContext" Scope: "IdlStruct"
		Array: IopServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_id", Type: "IOP::ServiceId" Scope: "IdlTypedef"
		ContextId: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ContextData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: 0,
	},
	},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopServiceContextList(
	//"StructDclAllParamsConstructorParamService"
	Array IopServiceContext) *IopServiceContextList {
	//noinspection GoRedundantConversion
	return &IopServiceContextList{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextListId_Const,
		},
		Array: Array,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopServiceContextList(randomGenerator __goidl__.IRandomDataGenerator) *IopServiceContextList {
	//noinspection GoRedundantConversion
	return &IopServiceContextList{
		IdlObject: __goidl__.IdlObject{
			Id: IopServiceContextListId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IOP::ServiceContext" Scope: "IdlStruct"
		Array: IopServiceContext{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_id", Type: "IOP::ServiceId" Scope: "IdlTypedef"
		ContextId: randomGenerator.UnsignedLongTypeValue(__reflect__.TypeOf((*IopServiceContextList)(nil)), "ContextId"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "context_data", Type: "CORBA::OctetSeq" Scope: "IdlStruct"
		ContextData: __goIdlCorba__.CorbaOctetSeq{
		IdlObject: __goidl__.IdlObject{
			Id: "ddd",
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "Array", Type: "IdlOctet" Scope: "IdlOctetKind"
		Array: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopServiceContextList)(nil)), "Array"),
	},
	},
	}
}

func (self *IopServiceContextList) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopServiceContextList) GoString() string {
	return self.String()
}

func (self *IopServiceContextList) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Array.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContextList) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContextList) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	return nil
}

//noinspection GoSnakeCaseUsage
type IopServiceContextList_Helper struct {
}

// Constant declaration: "IOP::TransactionService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTransactionService uint32 = 0

// Constant declaration: "IOP::CodeSets", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopCodeSets uint32 = 1

// Constant declaration: "IOP::ChainBypassCheck", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopChainBypassCheck uint32 = 2

// Constant declaration: "IOP::ChainBypassInfo", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopChainBypassInfo uint32 = 3

// Constant declaration: "IOP::LogicalThreadId", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopLogicalThreadId uint32 = 4

// Constant declaration: "IOP::BI_DIR_IIOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopBiDirIiop uint32 = 5

// Constant declaration: "IOP::SendingContextRunTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopSendingContextRunTime uint32 = 6

// Constant declaration: "IOP::INVOCATION_POLICIES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopInvocationPolicies uint32 = 7

// Constant declaration: "IOP::FORWARDED_IDENTITY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopForwardedIdentity uint32 = 8

// Constant declaration: "IOP::UnknownExceptionInfo", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopUnknownExceptionInfo uint32 = 9

// Constant declaration: "IOP::RTCorbaPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopRTCorbaPriority uint32 = 10

// Constant declaration: "IOP::RTCorbaPriorityRange", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopRTCorbaPriorityRange uint32 = 11

// Constant declaration: "IOP::FT_GROUP_VERSION", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopFtGroupVersion uint32 = 12

// Constant declaration: "IOP::FT_REQUEST", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopFtRequest uint32 = 13

// Constant declaration: "IOP::ExceptionDetailMessage", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopExceptionDetailMessage uint32 = 14

// Constant declaration: "IOP::SecurityAttributeService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopSecurityAttributeService uint32 = 15

// Constant declaration: "IOP::ActivityService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopActivityService uint32 = 16

// Exception declaration: "IOP::Codec::InvalidTypeForEncoding", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecInvalidTypeForEncoding struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecInvalidTypeForEncodingId_Const = "IDL:omg.org/IOP/Codec/InvalidTypeForEncoding:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopCodecInvalidTypeForEncoding() *IopCodecInvalidTypeForEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecInvalidTypeForEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecInvalidTypeForEncodingId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopCodecInvalidTypeForEncoding() *IopCodecInvalidTypeForEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecInvalidTypeForEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecInvalidTypeForEncodingId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopCodecInvalidTypeForEncoding() *IopCodecInvalidTypeForEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecInvalidTypeForEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecInvalidTypeForEncodingId_Const,
		},
	}
}

func (self *IopCodecInvalidTypeForEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecInvalidTypeForEncoding) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecInvalidTypeForEncoding(%v)", self.String())
}
func (self *IopCodecInvalidTypeForEncoding) GoString() string {
	return self.String()
}

func (self *IopCodecInvalidTypeForEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecInvalidTypeForEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecInvalidTypeForEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecInvalidTypeForEncoding_Helper struct {
}

// Exception declaration: "IOP::Codec::FormatMismatch", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecFormatMismatch struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecFormatMismatchId_Const = "IDL:omg.org/IOP/Codec/FormatMismatch:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopCodecFormatMismatch() *IopCodecFormatMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecFormatMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFormatMismatchId_Const,
		},
	}
}

func (self *IopCodecFormatMismatch) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFormatMismatch) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecFormatMismatch(%v)", self.String())
}
func (self *IopCodecFormatMismatch) GoString() string {
	return self.String()
}

func (self *IopCodecFormatMismatch) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFormatMismatch) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFormatMismatch) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFormatMismatch_Helper struct {
}

// Exception declaration: "IOP::Codec::TypeMismatch", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecTypeMismatch struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecTypeMismatchId_Const = "IDL:omg.org/IOP/Codec/TypeMismatch:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopCodecTypeMismatch() *IopCodecTypeMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecTypeMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecTypeMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopCodecTypeMismatch() *IopCodecTypeMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecTypeMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecTypeMismatchId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopCodecTypeMismatch() *IopCodecTypeMismatch {
	//noinspection GoRedundantConversion
	return &IopCodecTypeMismatch{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecTypeMismatchId_Const,
		},
	}
}

func (self *IopCodecTypeMismatch) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecTypeMismatch) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecTypeMismatch(%v)", self.String())
}
func (self *IopCodecTypeMismatch) GoString() string {
	return self.String()
}

func (self *IopCodecTypeMismatch) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecTypeMismatch) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecTypeMismatch) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecTypeMismatch_Helper struct {
}

// Interface declaration: "IOP::Codec", generatedBy by: "WriteInterface"
type IopCodec interface {
	// Interface operations
	//Exceptions for : Encode
	//	IopCodecInvalidTypeForEncoding
	// Original name: "encode"
	Encode(Data __goidl__.IdlAny) (result *__goIdlCorba__.CorbaOctetSeq, err error)
	//Exceptions for : Decode
	//	IopCodecFormatMismatch
	// Original name: "decode"
	Decode(Data *__goIdlCorba__.CorbaOctetSeq) (result __goidl__.IdlAny, err error)
	//Exceptions for : EncodeValue
	//	IopCodecInvalidTypeForEncoding
	// Original name: "encode_value"
	EncodeValue(Data __goidl__.IdlAny) (result *__goIdlCorba__.CorbaOctetSeq, err error)
	//Exceptions for : DecodeValue
	//	IopCodecFormatMismatch
	//	IopCodecTypeMismatch
	// Original name: "decode_value"
	DecodeValue(Data *__goIdlCorba__.CorbaOctetSeq, Tc __goIdlCorba__.CorbaTypeCode) (result __goidl__.IdlAny, err error)
}

//noinspection GoSnakeCaseUsage
type IopCodec_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopCodecId_Const = "IDL:omg.org/IOP/Codec:1.0"

func (self IopCodec_Helper) Id() string {
	return IopCodecId_Const
}

func (self IopCodec_Helper) Read(stream __goidl__.IReadAny) (IopCodec, error) {
	return nil, nil
}

func (self IopCodec_Helper) Write(stream __goidl__.IWriteAny, v IopCodec) error {
	return nil
}

// TypeDef declaration: "IOP::EncodingFormat", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::EncodingFormat" from: "int16"
type IopEncodingFormat int16

//noinspection GoSnakeCaseUsage
type IopEncodingFormat_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopEncodingFormatId_Const = "IDL:omg.org/IOP/EncodingFormat:1.0"

func (self IopEncodingFormat_Helper) Id() string {
	return IopEncodingFormatId_Const
}

func (self IopEncodingFormat_Helper) Read(stream __goidl__.IReadAny) (int16, error) {
	result, err := __goidl__.IdlInt16Helper.Read(stream)
	return result, err
}

func (self IopEncodingFormat_Helper) Write(stream __goidl__.IWriteAny, v int16) error {
	return __goidl__.IdlInt16Helper.Write(stream, v)
}

// Constant declaration: "IOP::ENCODING_CDR_ENCAPS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopEncodingCdrEncaps int16 = 0

// Struct declaration: "IOP::Encoding", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopEncoding struct {
	__goidl__.IdlObject
	Format int16 `json:"Format"`
	MajorVersion byte `json:"MajorVersion"`
	MinorVersion byte `json:"MinorVersion"`
}

//noinspection GoSnakeCaseUsage
const IopEncodingId_Const = "IDL:omg.org/IOP/Encoding:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopEncoding() *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "format", Type: "IOP::EncodingFormat" Scope: "IdlTypedef"
		Format: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MajorVersion: 0,
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MinorVersion: 0,
	}
}

//noinspection GoUnusedExportedFunction
func NewIopEncoding(
	//"StructDclAllParamsConstructorParamService"
	Format int16,
	//"StructDclAllParamsConstructorParamService"
	MajorVersion byte,
	//"StructDclAllParamsConstructorParamService"
	MinorVersion byte) *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		Format: Format,
		MajorVersion: MajorVersion,
		MinorVersion: MinorVersion,
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopEncoding(randomGenerator __goidl__.IRandomDataGenerator) *IopEncoding {
	//noinspection GoRedundantConversion
	return &IopEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopEncodingId_Const,
		},
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "format", Type: "IOP::EncodingFormat" Scope: "IdlTypedef"
		Format: randomGenerator.ShortTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "Format"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "major_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MajorVersion: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "MajorVersion"),
		// "StructDclDefaultConstructorMemberDefaultValueService", MemberName: "minor_version", Type: "IdlOctet" Scope: "IdlOctetKind"
		MinorVersion: randomGenerator.OctetTypeValue(__reflect__.TypeOf((*IopEncoding)(nil)), "MinorVersion"),
	}
}

func (self *IopEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopEncoding) GoString() string {
	return self.String()
}

func (self *IopEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(ShortType)
	self.Format, err = __goidl__.IdlInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MajorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MinorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(ShortType)
	err = __goidl__.IdlInt16Helper.Write(stream, self.Format)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MajorVersion)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MinorVersion)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopEncoding_Helper struct {
}

// Exception declaration: "IOP::CodecFactory::UnknownEncoding", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecFactoryUnknownEncoding struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryUnknownEncodingId_Const = "IDL:omg.org/IOP/CodecFactory/UnknownEncoding:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultIopCodecFactoryUnknownEncoding() *IopCodecFactoryUnknownEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecFactoryUnknownEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFactoryUnknownEncodingId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewIopCodecFactoryUnknownEncoding() *IopCodecFactoryUnknownEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecFactoryUnknownEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFactoryUnknownEncodingId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomIopCodecFactoryUnknownEncoding() *IopCodecFactoryUnknownEncoding {
	//noinspection GoRedundantConversion
	return &IopCodecFactoryUnknownEncoding{
		IdlObject: __goidl__.IdlObject{
			Id: IopCodecFactoryUnknownEncodingId_Const,
		},
	}
}

func (self *IopCodecFactoryUnknownEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFactoryUnknownEncoding) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecFactoryUnknownEncoding(%v)", self.String())
}
func (self *IopCodecFactoryUnknownEncoding) GoString() string {
	return self.String()
}

func (self *IopCodecFactoryUnknownEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryUnknownEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryUnknownEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFactoryUnknownEncoding_Helper struct {
}

// Interface declaration: "IOP::CodecFactory", generatedBy by: "WriteInterface"
type IopCodecFactory interface {
	// Interface operations
	//Exceptions for : CreateCodec
	//	IopCodecFactoryUnknownEncoding
	// Original name: "create_codec"
	CreateCodec(Enc *IopEncoding) (result IopCodec, err error)
}

//noinspection GoSnakeCaseUsage
type IopCodecFactory_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryId_Const = "IDL:omg.org/IOP/CodecFactory:1.0"

func (self IopCodecFactory_Helper) Id() string {
	return IopCodecFactoryId_Const
}

func (self IopCodecFactory_Helper) Read(stream __goidl__.IReadAny) (IopCodecFactory, error) {
	return nil, nil
}

func (self IopCodecFactory_Helper) Write(stream __goidl__.IWriteAny, v IopCodecFactory) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var IopProfileIdHelper = IopProfileId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopTaggedProfileHelper = IopTaggedProfile_Helper{}

//noinspection GoUnusedGlobalVariable
var IopTaggedProfileSeqHelper = IopTaggedProfileSeq_Helper{}

//noinspection GoUnusedGlobalVariable
var IopIorHelper = IopIor_Helper{}

//noinspection GoUnusedGlobalVariable
var IopComponentIdHelper = IopComponentId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopComponentDataHelper = IopComponentData_Helper{}

//noinspection GoUnusedGlobalVariable
var IopTaggedComponentHelper = IopTaggedComponent_Helper{}

//noinspection GoUnusedGlobalVariable
var IopTaggedComponentSeqHelper = IopTaggedComponentSeq_Helper{}

//noinspection GoUnusedGlobalVariable
var IopMultipleComponentProfileHelper = IopMultipleComponentProfile_Helper{}

//noinspection GoUnusedGlobalVariable
var IopObjectKeyHelper = IopObjectKey_Helper{}

//noinspection GoUnusedGlobalVariable
var IopServiceIdHelper = IopServiceId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopServiceContextHelper = IopServiceContext_Helper{}

//noinspection GoUnusedGlobalVariable
var IopServiceContextListHelper = IopServiceContextList_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecInvalidTypeForEncodingHelper = IopCodecInvalidTypeForEncoding_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecFormatMismatchHelper = IopCodecFormatMismatch_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecTypeMismatchHelper = IopCodecTypeMismatch_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecHelper = IopCodec_Helper{}

//noinspection GoUnusedGlobalVariable
var IopEncodingFormatHelper = IopEncodingFormat_Helper{}

//noinspection GoUnusedGlobalVariable
var IopEncodingHelper = IopEncoding_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecFactoryUnknownEncodingHelper = IopCodecFactoryUnknownEncoding_Helper{}

//noinspection GoUnusedGlobalVariable
var IopCodecFactoryHelper = IopCodecFactory_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedProfileId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopTaggedProfile()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopTaggedProfile(generator)
			},
			__reflect__.TypeOf((*IopTaggedProfile)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedProfileSeqId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopTaggedProfileSeq()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopTaggedProfileSeq(generator)
			},
			__reflect__.TypeOf((*IopTaggedProfileSeq)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopIorId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopIor()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopIor(generator)
			},
			__reflect__.TypeOf((*IopIor)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopComponentDataId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopComponentData()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopComponentData()
			},
			__reflect__.TypeOf((*IopComponentData)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedComponentId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopTaggedComponent()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopTaggedComponent(generator)
			},
			__reflect__.TypeOf((*IopTaggedComponent)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedComponentSeqId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopTaggedComponentSeq()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopTaggedComponentSeq(generator)
			},
			__reflect__.TypeOf((*IopTaggedComponentSeq)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopMultipleComponentProfileId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopMultipleComponentProfile()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopMultipleComponentProfile(generator)
			},
			__reflect__.TypeOf((*IopMultipleComponentProfile)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopObjectKeyId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopObjectKey()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopObjectKey()
			},
			__reflect__.TypeOf((*IopObjectKey)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopServiceContextId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopServiceContext()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopServiceContext(generator)
			},
			__reflect__.TypeOf((*IopServiceContext)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopServiceContextListId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopServiceContextList()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopServiceContextList(generator)
			},
			__reflect__.TypeOf((*IopServiceContextList)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecInvalidTypeForEncodingId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopCodecInvalidTypeForEncoding()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopCodecInvalidTypeForEncoding()
			},
			__reflect__.TypeOf((*IopCodecInvalidTypeForEncoding)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFormatMismatchId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopCodecFormatMismatch()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopCodecFormatMismatch()
			},
			__reflect__.TypeOf((*IopCodecFormatMismatch)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecTypeMismatchId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopCodecTypeMismatch()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopCodecTypeMismatch()
			},
			__reflect__.TypeOf((*IopCodecTypeMismatch)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopEncodingId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopEncoding()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewRandomIopEncoding(generator)
			},
			__reflect__.TypeOf((*IopEncoding)(nil))))
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFactoryUnknownEncodingId_Const,
			__yaccidl__.IdlStruct,
			"IOP.idl.go",
			func() __goidl__.IIdlObject {
				return NewDefaultIopCodecFactoryUnknownEncoding()
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return NewDefaultIopCodecFactoryUnknownEncoding()
			},
			__reflect__.TypeOf((*IopCodecFactoryUnknownEncoding)(nil))))
}
