// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"

// TypeDef declaration: "IOP::ProfileId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ProfileId" from: "uint32"
type IopProfileId uint32

//noinspection GoSnakeCaseUsage
type IopProfileId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopProfileIdId_Const = "IDL:omg.org/IOP/ProfileId:1.0"

func (self IopProfileId_Helper) Id() string {
	return IopProfileIdId_Const
}

func (self IopProfileId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopProfileId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Constant declaration: "IOP::TAG_INTERNET_IOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInternetIop uint32 = 0

// Constant declaration: "IOP::TAG_MULTIPLE_COMPONENTS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagMultipleComponents uint32 = 1

// Constant declaration: "IOP::TAG_SCCP_IOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSccpIop uint32 = 2

// Constant declaration: "IOP::TAG_UIPMC", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagUipmc uint32 = 3

// TypeDef declaration: "IOP::ComponentId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ComponentId" from: "uint32"
type IopComponentId uint32

//noinspection GoSnakeCaseUsage
type IopComponentId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopComponentIdId_Const = "IDL:omg.org/IOP/ComponentId:1.0"

func (self IopComponentId_Helper) Id() string {
	return IopComponentIdId_Const
}

func (self IopComponentId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopComponentId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Constant declaration: "IOP::TAG_ORB_TYPE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagOrbType uint32 = 0

// Constant declaration: "IOP::TAG_CODE_SETS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCodeSets uint32 = 1

// Constant declaration: "IOP::TAG_POLICIES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagPolicies uint32 = 2

// Constant declaration: "IOP::TAG_ALTERNATE_IIOP_ADDRESS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagAlternateIiopAddress uint32 = 3

// Constant declaration: "IOP::TAG_ASSOCIATION_OPTIONS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagAssociationOptions uint32 = 13

// Constant declaration: "IOP::TAG_SEC_NAME", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSecName uint32 = 14

// Constant declaration: "IOP::TAG_SPKM_1_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSpkm1SecMech uint32 = 15

// Constant declaration: "IOP::TAG_SPKM_2_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSpkm2SecMech uint32 = 16

// Constant declaration: "IOP::TAG_KerberosV5_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagKerberosV5SecMech uint32 = 17

// Constant declaration: "IOP::TAG_CSI_ECMA_Secret_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaSecretSecMech uint32 = 18

// Constant declaration: "IOP::TAG_CSI_ECMA_Hybrid_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaHybridSecMech uint32 = 19

// Constant declaration: "IOP::TAG_SSL_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSslSecTrans uint32 = 20

// Constant declaration: "IOP::TAG_CSI_ECMA_Public_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiEcmaPublicSecMech uint32 = 21

// Constant declaration: "IOP::TAG_GENERIC_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGenericSecMech uint32 = 22

// Constant declaration: "IOP::TAG_FIREWALL_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagFirewallTrans uint32 = 23

// Constant declaration: "IOP::TAG_SCCP_CONTACT_INFO", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSccpContactInfo uint32 = 24

// Constant declaration: "IOP::TAG_JAVA_CODEBASE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagJavaCodebase uint32 = 25

// Constant declaration: "IOP::TAG_TRANSACTION_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagTransactionPolicy uint32 = 26

// Constant declaration: "IOP::TAG_MESSAGE_ROUTER", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagMessageRouter uint32 = 30

// Constant declaration: "IOP::TAG_OTS_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagOtsPolicy uint32 = 31

// Constant declaration: "IOP::TAG_INV_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInvPolicy uint32 = 32

// Constant declaration: "IOP::TAG_CSI_SEC_MECH_LIST", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCsiSecMechList uint32 = 33

// Constant declaration: "IOP::TAG_NULL_TAG", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagNullTag uint32 = 34

// Constant declaration: "IOP::TAG_SECIOP_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagSeciopSecTrans uint32 = 35

// Constant declaration: "IOP::TAG_TLS_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagTlsSecTrans uint32 = 36

// Constant declaration: "IOP::TAG_ACTIVITY_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagActivityPolicy uint32 = 37

// Constant declaration: "IOP::TAG_RMI_CUSTOM_MAX_STREAM_FORMAT", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagRmiCustomMaxStreamFormat uint32 = 38

// Constant declaration: "IOP::TAG_GROUP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGroup uint32 = 39

// Constant declaration: "IOP::TAG_GROUP_IIOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagGroupIiop uint32 = 40

// Constant declaration: "IOP::TAG_COMPLETE_OBJECT_KEY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagCompleteObjectKey uint32 = 5

// Constant declaration: "IOP::TAG_ENDPOINT_ID_POSITION", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagEndpointIdPosition uint32 = 6

// Constant declaration: "IOP::TAG_LOCATION_POLICY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagLocationPolicy uint32 = 12

// Constant declaration: "IOP::TAG_DCE_STRING_BINDING", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceStringBinding uint32 = 100

// Constant declaration: "IOP::TAG_DCE_BINDING_NAME", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceBindingName uint32 = 101

// Constant declaration: "IOP::TAG_DCE_NO_PIPES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceNoPipes uint32 = 102

// Constant declaration: "IOP::TAG_DCE_SEC_MECH", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagDceSecMech uint32 = 103

// Constant declaration: "IOP::TAG_INET_SEC_TRANS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTagInetSecTrans uint32 = 123

// TypeDef declaration: "IOP::ServiceId", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::ServiceId" from: "uint32"
type IopServiceId uint32

//noinspection GoSnakeCaseUsage
type IopServiceId_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopServiceIdId_Const = "IDL:omg.org/IOP/ServiceId:1.0"

func (self IopServiceId_Helper) Id() string {
	return IopServiceIdId_Const
}

func (self IopServiceId_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self IopServiceId_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}

// Constant declaration: "IOP::TransactionService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopTransactionService uint32 = 0

// Constant declaration: "IOP::CodeSets", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopCodeSets uint32 = 1

// Constant declaration: "IOP::ChainBypassCheck", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopChainBypassCheck uint32 = 2

// Constant declaration: "IOP::ChainBypassInfo", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopChainBypassInfo uint32 = 3

// Constant declaration: "IOP::LogicalThreadId", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopLogicalThreadId uint32 = 4

// Constant declaration: "IOP::BI_DIR_IIOP", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopBiDirIiop uint32 = 5

// Constant declaration: "IOP::SendingContextRunTime", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopSendingContextRunTime uint32 = 6

// Constant declaration: "IOP::INVOCATION_POLICIES", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopInvocationPolicies uint32 = 7

// Constant declaration: "IOP::FORWARDED_IDENTITY", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopForwardedIdentity uint32 = 8

// Constant declaration: "IOP::UnknownExceptionInfo", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopUnknownExceptionInfo uint32 = 9

// Constant declaration: "IOP::RTCorbaPriority", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopRTCorbaPriority uint32 = 10

// Constant declaration: "IOP::RTCorbaPriorityRange", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopRTCorbaPriorityRange uint32 = 11

// Constant declaration: "IOP::FT_GROUP_VERSION", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopFtGroupVersion uint32 = 12

// Constant declaration: "IOP::FT_REQUEST", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopFtRequest uint32 = 13

// Constant declaration: "IOP::ExceptionDetailMessage", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopExceptionDetailMessage uint32 = 14

// Constant declaration: "IOP::SecurityAttributeService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopSecurityAttributeService uint32 = 15

// Constant declaration: "IOP::ActivityService", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopActivityService uint32 = 16

// TypeDef declaration: "IOP::EncodingFormat", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "IOP::EncodingFormat" from: "int16"
type IopEncodingFormat int16

//noinspection GoSnakeCaseUsage
type IopEncodingFormat_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopEncodingFormatId_Const = "IDL:omg.org/IOP/EncodingFormat:1.0"

func (self IopEncodingFormat_Helper) Id() string {
	return IopEncodingFormatId_Const
}

func (self IopEncodingFormat_Helper) Read(stream __goidl__.IReadAny) (int16, error) {
	result, err := __goidl__.IdlInt16Helper.Read(stream)
	return result, err
}

func (self IopEncodingFormat_Helper) Write(stream __goidl__.IWriteAny, v int16) error {
	return __goidl__.IdlInt16Helper.Write(stream, v)
}

// Constant declaration: "IOP::ENCODING_CDR_ENCAPS", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const IopEncodingCdrEncaps int16 = 0


//noinspection GoUnusedGlobalVariable
var IopProfileIdHelper = IopProfileId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopComponentIdHelper = IopComponentId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopServiceIdHelper = IopServiceId_Helper{}

//noinspection GoUnusedGlobalVariable
var IopEncodingFormatHelper = IopEncodingFormat_Helper{}

func init() {
}
