// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Encoding", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopEncoding struct {
	__goidl__.IdlObject
	Format int16 `json:"Format"`
	MajorVersion byte `json:"MajorVersion"`
	MinorVersion byte `json:"MinorVersion"`
}

//noinspection GoSnakeCaseUsage
const IopEncodingId_Const = "IDL:omg.org/IOP/Encoding:1.0"

func (self *IopEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopEncoding) GoString() string {
	return self.String()
}

func (self *IopEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(ShortType)
	self.Format, err = __goidl__.IdlInt16Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MajorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlOctetKind)
	self.MinorVersion, err = __goidl__.IdlOctetHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(ShortType)
	err = __goidl__.IdlInt16Helper.Write(stream, self.Format)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MajorVersion)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlOctetKind)
	err = __goidl__.IdlOctetHelper.Write(stream, self.MinorVersion)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopEncoding_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopEncodingHelper = IopEncoding_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopEncodingId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopEncoding.go",
			func() __goidl__.IIdlObject {
				return &IopEncoding{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopEncoding{}
			},
			__reflect__.TypeOf((*IopEncoding)(nil))))
}
