// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::CodecFactory_create_codec_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecFactoryCreateCodecIn struct {
	__goidl__.IdlObject
	Enc IopEncoding `json:"Enc"`
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryCreateCodecInId_Const = "IDL:IOP/CodecFactory_create_codec_In:1.0"

func (self *IopCodecFactoryCreateCodecIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFactoryCreateCodecIn) GoString() string {
	return self.String()
}

func (self *IopCodecFactoryCreateCodecIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Enc.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryCreateCodecIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryCreateCodecIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Enc.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFactoryCreateCodecIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecFactoryCreateCodecInHelper = IopCodecFactoryCreateCodecIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFactoryCreateCodecInId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecFactoryCreateCodecIn.go",
			func() __goidl__.IIdlObject {
				return &IopCodecFactoryCreateCodecIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecFactoryCreateCodecIn{}
			},
			__reflect__.TypeOf((*IopCodecFactoryCreateCodecIn)(nil))))
}
