// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::CodecFactory_create_codec_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecFactoryCreateCodecOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryCreateCodecOutId_Const = "IDL:IOP/CodecFactory_create_codec_Out:1.0"

func (self *IopCodecFactoryCreateCodecOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFactoryCreateCodecOut) GoString() string {
	return self.String()
}

func (self *IopCodecFactoryCreateCodecOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryCreateCodecOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryCreateCodecOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFactoryCreateCodecOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecFactoryCreateCodecOutHelper = IopCodecFactoryCreateCodecOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFactoryCreateCodecOutId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecFactoryCreateCodecOut.go",
			func() __goidl__.IIdlObject {
				return &IopCodecFactoryCreateCodecOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecFactoryCreateCodecOut{}
			},
			__reflect__.TypeOf((*IopCodecFactoryCreateCodecOut)(nil))))
}
