// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goIdlCorba__ "github.com/bhbosman/goIdlCorba"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::ComponentData", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopComponentData struct {
	__goIdlCorba__.CorbaOctetSeq
}

//noinspection GoSnakeCaseUsage
const IopComponentDataId_Const = "IDL:IOP/ComponentData:1.0"

func (self *IopComponentData) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopComponentData) GoString() string {
	return self.String()
}

func (self *IopComponentData) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.CorbaOctetSeq.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopComponentData) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopComponentData) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.CorbaOctetSeq.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopComponentData_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopComponentDataHelper = IopComponentData_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopComponentDataId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopComponentData.go",
			func() __goidl__.IIdlObject {
				return &IopComponentData{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopComponentData{}
			},
			__reflect__.TypeOf((*IopComponentData)(nil))))
}
