// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_decode_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecDecodeOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecDecodeOutId_Const = "IDL:IOP/Codec_decode_Out:1.0"

func (self *IopCodecDecodeOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecDecodeOut) GoString() string {
	return self.String()
}

func (self *IopCodecDecodeOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecDecodeOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecDecodeOutHelper = IopCodecDecodeOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecDecodeOutId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecDecodeOut.go",
			func() __goidl__.IIdlObject {
				return &IopCodecDecodeOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecDecodeOut{}
			},
			__reflect__.TypeOf((*IopCodecDecodeOut)(nil))))
}
