// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_encode_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecEncodeIn struct {
	__goidl__.IdlObject
	Data __goidl__.IdlAny `json:"Data"`
}

//noinspection GoSnakeCaseUsage
const IopCodecEncodeInId_Const = "IDL:IOP/Codec_encode_In:1.0"

func (self *IopCodecEncodeIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecEncodeIn) GoString() string {
	return self.String()
}

func (self *IopCodecEncodeIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.Data, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.Data)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecEncodeIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecEncodeInHelper = IopCodecEncodeIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecEncodeInId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecEncodeIn.go",
			func() __goidl__.IIdlObject {
				return &IopCodecEncodeIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecEncodeIn{}
			},
			__reflect__.TypeOf((*IopCodecEncodeIn)(nil))))
}
