// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goIdlCorba__ "github.com/bhbosman/goIdlCorba"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_decode_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecDecodeIn struct {
	__goidl__.IdlObject
	Data __goIdlCorba__.CorbaOctetSeq `json:"Data"`
}

//noinspection GoSnakeCaseUsage
const IopCodecDecodeInId_Const = "IDL:IOP/Codec_decode_In:1.0"

func (self *IopCodecDecodeIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecDecodeIn) GoString() string {
	return self.String()
}

func (self *IopCodecDecodeIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.Data.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.Data.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecDecodeIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecDecodeInHelper = IopCodecDecodeIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecDecodeInId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecDecodeIn.go",
			func() __goidl__.IIdlObject {
				return &IopCodecDecodeIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecDecodeIn{}
			},
			__reflect__.TypeOf((*IopCodecDecodeIn)(nil))))
}
