// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_encode_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecEncodeOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecEncodeOutId_Const = "IDL:IOP/Codec_encode_Out:1.0"

func (self *IopCodecEncodeOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecEncodeOut) GoString() string {
	return self.String()
}

func (self *IopCodecEncodeOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecEncodeOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecEncodeOutHelper = IopCodecEncodeOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecEncodeOutId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecEncodeOut.go",
			func() __goidl__.IIdlObject {
				return &IopCodecEncodeOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecEncodeOut{}
			},
			__reflect__.TypeOf((*IopCodecEncodeOut)(nil))))
}
