// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_encode_value_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecEncodeValueOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecEncodeValueOutId_Const = "IDL:IOP/Codec_encode_value_Out:1.0"

func (self *IopCodecEncodeValueOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecEncodeValueOut) GoString() string {
	return self.String()
}

func (self *IopCodecEncodeValueOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeValueOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeValueOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecEncodeValueOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecEncodeValueOutHelper = IopCodecEncodeValueOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecEncodeValueOutId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecEncodeValueOut.go",
			func() __goidl__.IIdlObject {
				return &IopCodecEncodeValueOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecEncodeValueOut{}
			},
			__reflect__.TypeOf((*IopCodecEncodeValueOut)(nil))))
}
