// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goIdlCorba__ "github.com/bhbosman/goIdlCorba"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::ServiceContext", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopServiceContext struct {
	__goidl__.IdlObject
	ContextId uint32 `json:"ContextId"`
	ContextData __goIdlCorba__.CorbaOctetSeq `json:"ContextData"`
}

//noinspection GoSnakeCaseUsage
const IopServiceContextId_Const = "IDL:omg.org/IOP/ServiceContext:1.0"

func (self *IopServiceContext) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopServiceContext) GoString() string {
	return self.String()
}

func (self *IopServiceContext) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.ContextId, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ContextData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContext) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopServiceContext) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.ContextId)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ContextData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopServiceContext_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopServiceContextHelper = IopServiceContext_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopServiceContextId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopServiceContext.go",
			func() __goidl__.IIdlObject {
				return &IopServiceContext{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopServiceContext{}
			},
			__reflect__.TypeOf((*IopServiceContext)(nil))))
}
