// Code generated by me. DO NOT EDIT.

package goIdlIop

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Exception declaration: "IOP::CodecFactory::UnknownEncoding", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type IopCodecFactoryUnknownEncoding struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryUnknownEncodingId_Const = "IDL:omg.org/IOP/CodecFactory/UnknownEncoding:1.0"

func (self *IopCodecFactoryUnknownEncoding) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecFactoryUnknownEncoding) Error() string{
	return 	__fmt__.Sprintf("Error of type IopCodecFactoryUnknownEncoding(%v)", self.String())
}
func (self *IopCodecFactoryUnknownEncoding) GoString() string {
	return self.String()
}

func (self *IopCodecFactoryUnknownEncoding) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryUnknownEncoding) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecFactoryUnknownEncoding) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecFactoryUnknownEncoding_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecFactoryUnknownEncodingHelper = IopCodecFactoryUnknownEncoding_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecFactoryUnknownEncodingId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecFactoryUnknownEncoding.go",
			func() __goidl__.IIdlObject {
				return &IopCodecFactoryUnknownEncoding{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecFactoryUnknownEncoding{}
			},
			__reflect__.TypeOf((*IopCodecFactoryUnknownEncoding)(nil))))
}
