// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_decode_value_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecDecodeValueOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const IopCodecDecodeValueOutId_Const = "IDL:IOP/Codec_decode_value_Out:1.0"

func (self *IopCodecDecodeValueOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecDecodeValueOut) GoString() string {
	return self.String()
}

func (self *IopCodecDecodeValueOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeValueOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecDecodeValueOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecDecodeValueOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecDecodeValueOutHelper = IopCodecDecodeValueOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecDecodeValueOutId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecDecodeValueOut.go",
			func() __goidl__.IIdlObject {
				return &IopCodecDecodeValueOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecDecodeValueOut{}
			},
			__reflect__.TypeOf((*IopCodecDecodeValueOut)(nil))))
}
