// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::Codec_encode_value_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopCodecEncodeValueIn struct {
	__goidl__.IdlObject
	Data __goidl__.IdlAny `json:"Data"`
}

//noinspection GoSnakeCaseUsage
const IopCodecEncodeValueInId_Const = "IDL:IOP/Codec_encode_value_In:1.0"

func (self *IopCodecEncodeValueIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopCodecEncodeValueIn) GoString() string {
	return self.String()
}

func (self *IopCodecEncodeValueIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(AnyType)
	self.Data, err = __goidl__.IdlAnyHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeValueIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopCodecEncodeValueIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(AnyType)
	err = __goidl__.IdlAnyHelper.Write(stream, self.Data)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopCodecEncodeValueIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopCodecEncodeValueInHelper = IopCodecEncodeValueIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopCodecEncodeValueInId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopCodecEncodeValueIn.go",
			func() __goidl__.IIdlObject {
				return &IopCodecEncodeValueIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopCodecEncodeValueIn{}
			},
			__reflect__.TypeOf((*IopCodecEncodeValueIn)(nil))))
}
