// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goIdlCorba__ "github.com/bhbosman/goIdlCorba"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::TaggedProfile", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedProfile struct {
	__goidl__.IdlObject
	Tag uint32 `json:"Tag"`
	ProfileData __goIdlCorba__.CorbaOctetSeq `json:"ProfileData"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedProfileId_Const = "IDL:omg.org/IOP/TaggedProfile:1.0"

func (self *IopTaggedProfile) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedProfile) GoString() string {
	return self.String()
}

func (self *IopTaggedProfile) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Tag, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ProfileData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfile) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedProfile) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Tag)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ProfileData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedProfile_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopTaggedProfileHelper = IopTaggedProfile_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedProfileId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopTaggedProfile.go",
			func() __goidl__.IIdlObject {
				return &IopTaggedProfile{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopTaggedProfile{}
			},
			__reflect__.TypeOf((*IopTaggedProfile)(nil))))
}
