// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "IOP::TaggedComponent", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type IopTaggedComponent struct {
	__goidl__.IdlObject
	Tag uint32 `json:"Tag"`
	ComponentData IopComponentData `json:"ComponentData"`
}

//noinspection GoSnakeCaseUsage
const IopTaggedComponentId_Const = "IDL:omg.org/IOP/TaggedComponent:1.0"

func (self *IopTaggedComponent) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *IopTaggedComponent) GoString() string {
	return self.String()
}

func (self *IopTaggedComponent) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Tag, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ComponentData.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponent) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *IopTaggedComponent) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Tag)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ComponentData.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type IopTaggedComponent_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var IopTaggedComponentHelper = IopTaggedComponent_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			IopTaggedComponentId_Const,
			__goidl__.StructType,
			"IOP.idl",
			"xdl_IopTaggedComponent.go",
			func() __goidl__.IIdlObject {
				return &IopTaggedComponent{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &IopTaggedComponent{}
			},
			__reflect__.TypeOf((*IopTaggedComponent)(nil))))
}
