// Code generated by me. DO NOT EDIT.

package goIdlIop

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "IOP::CodecFactory", generatedBy by: "WriteInterface"
type IopCodecFactory interface {
	//Exceptions for : CreateCodec
	//	IopCodecFactoryUnknownEncoding
	// Original name: "create_codec"
	CreateCodec(params IopCodecFactoryCreateCodecIn) (IopCodecFactoryCreateCodecOut, error)
}

const IopCodecFactoryCreateCodecOperation = "create_codec"
//noinspection GoSnakeCaseUsage
type IopCodecFactory_Helper struct {
}

//noinspection GoSnakeCaseUsage
const IopCodecFactoryId_Const = "IDL:omg.org/IOP/CodecFactory:1.0"

func (self IopCodecFactory_Helper) Id() string {
	return IopCodecFactoryId_Const
}

func (self IopCodecFactory_Helper) Read(stream __goidl__.IReadAny) (IopCodecFactory, error) {
	return nil, nil
}

func (self IopCodecFactory_Helper) Write(stream __goidl__.IWriteAny, v IopCodecFactory) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var IopCodecFactoryHelper = IopCodecFactory_Helper{}

func init() {
}
